# Generated by Django 4.2.1 on 2023-05-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscan', '0006_remove_order_address_remove_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
