# Generated by Django 4.2.1 on 2023-05-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookscan', '0011_products_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
    ]
