# Generated by Django 4.1 on 2024-03-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscan', '0012_remove_products_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='banner')),
            ],
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
