# Generated by Django 4.1 on 2024-03-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookscan', '0013_banner_alter_contactdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
